language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

env:
  global:
  # DOCKER_USER + DOCKER_PASS
  - secure: "wCjmWYtOag43bzNzG+QohJoSewQT0BnDKRO4tJ3/+Mh/JEritmgHMELLRIqxyPfgsQdnBa4bRMDvJKIxBfR6VH36gLlBPG4TN/y1yTWkLagONrcAWcZeMv+I+HuZd/LRMbhAyHirOEtZxvAnw7/wfa8N7UV2leh9ZizJNO0QB88mCh5TZK7IVruK3IUepyhEzVvmVFNHWzSIKQN5I2zVX3hGfmqiNdEh8jf1GXz8EzVD69CJxrCw9L0DGvUk4PoRqtScEedkOjWznMAs6MTDtankAHZMPfgsMKeZUp9TeDL+/U336AXCvEBgOJWFYGmP3b9PBl2H4lQOH+8mKpny5+/gxuyL9t9ZD6gT60G+J+Gof/s+jTEazxKk4f2IXbg6aCVNraX4xD2yX1CgvxAmydKE2f6Q6c3NnQ44Ok1eOVVtphsttraKkYTOs9Qe2m2URuQLIfGkys4TAoiguyTqHSGQqgy7Zr6npcyc0E+iktu70VUGgiN+jG7GAYfnJzCSUoEHP6iBQ1uOC5R2sIuKIm7Dqb9h2Yp0JE+dpLVP84+ehiw5N3dX11UEDk060q85rQb1azXmDMcGPHVYsL0Dlqsj3XXjXdnadzBzSFee2LB1ZruweLd+mNLpq9FeMu04I0WUcMUjlFGvZbsGkROJ5q2y1/hqMljj3C936oEY4js="
  - secure: "WBCfSJvutzQIiOnCxVszzFR/+/bCLW+Z0Zu754RcClVQxm9bIzQesMyE3DV4sY/tObD5g6PXiISvaJKAK5lXyrJk9AAhsXu+dhGXidgasHW1XO8ryuEaV/SKPFmnXY0ctTDslGL2VYKem0FoyT5fv1z/SYLLJLECBmEmdpcVTV5BmUHF24KPlUCfd1KvRZyj3rtRIigKJ14svxKuYSbXo8ncQFSM3I24NJdNBqdZnG1dxb1U1jTcOW342YTLlNRU+zfup+JezBj8Q4uvrGpWT5lMXdm25QcO2QVxBu4gef+GRGL1Hw9Gh4jj4z+ctWKmRxKP/q1987CAs4ziYXIBR8H4RgVbwj3Mc7z/gUS8FQvWmDymu4OJjmbNpyS2xmB7m3LsNzOfL7gdJEBHZfo47mW8l3KRtzKnSXaV6Aez7AQqkjn/iL7AUVvzj2nsNUSKrVVHKdpBp9JnkW+idC0bqBjaGgSbUj3Roj5FNypsikKbd5mQdoTxSDoso/ewOO5h08dKpdkWRCA5xwk33AoyruTPenkkRYvCAHwzfXjSs1VtBOIarj2O5O1g+GO5aXFYmAUdrurxhfTfweZYrJggIhIQmNsrxQapAV55zwoIBrR0nk1hRgHhbR9IloOAEavrT4/WFCgQfeT0JGtx6Xg8MILeS0Na1U5DkDeH0a74+qY="
  - COMMIT=${TRAVIS_COMMIT::7}

script:
- ./mvnw clean install -B

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/k8s-spring-boot-demo
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME